name: docker-1
version: 1.0.2
versioned_at: 2026-08-31 19:29
description: Reusable Docker image and container conventions.
entrypoint: README.md
dependencies:
  - name: meta
    version: 1.0.2
    constraint: compatible
